baseURL = "https://blog.manas-mishra.com"
languageCode = 'en-us'
title = 'Manas Mishra'

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]